### ISSUE TITLE
Validation : need an option to set custom error message

### ISSUE THREAD

**Issue by shawon1fb** [daison12006013/gorvel#10]
user should have an easy way to set his/her own error message

**Comment by daison12006013** [comment]
```go
type Rule interface {
	ErrorMessage(inputField string, inputValue string) string
	Valid(inputField string, inputValue string) bool
}
```

A go dev should be able to create their own rule, that's the right way.
What I can think of is to prepare the existing "Validators/Must" to have a set of messages.

**Comment by daison12006013** [comment]
As of today, this is added as part of translations too and closure based.
