### ISSUE TITLE
 panic serving 127.0.0.1:61893: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by shawon1fb** [daison12006013/gorvel#3]
code breakes when gorvel_session is null

![Screenshot 2022-03-12 at 12 56 04 PM](https://user-images.githubusercontent.com/37122193/158007752-465e70a2-e8b6-45a7-994b-000bdc3bd899.png)

**Comment by shawon1fb** [comment]
![Screenshot 2022-03-12 at 1 01 11 PM](https://user-images.githubusercontent.com/37122193/158007831-221574fa-f4f5-4da7-b81b-c6e0511525f7.png)

**Comment by daison12006013** [comment]
Thanks @shawon1fb for debugging this, let me try replicate it
